### ISSUE TITLE
cabinet mix db fail

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#289]
yea it skipped room 7, 10, 14 and 11 in the .yaml file for some reason.

[mixcabinetsindb.bas](https://github.com/curif/AgeOfJoy-2022.1/blob/0.5.0/AGEBasicTests/config/mixcabinetsindb.bas) don't mix all the cabinets.

![image](https://github.com/curif/AgeOfJoy-2022.1/assets/8068749/089e87fc-0754-4576-9708-9cde35077ae9)

```
registry:
- cabinetDBName: undrfire
  rom: 
  room: ROOM001
  position: 0
- cabinetDBName: msword
  rom: 
  room: ROOM001
  position: 1
- cabinetDBName: galaga
  rom: 
  room: ROOM001
  position: 2
- cabinetDBName: spacegun
  rom: 
  room: ROOM001
  position: 3
- cabinetDBName: buckrog
  rom: 
  room: ROOM001
  position: 5
- cabinetDBName: sidearms
  rom: 
  room: ROOM001
  position: 6
- cabinetDBName: mslug4
  rom: 
  room: ROOM002
  position: 0
- cabinetDBName: opwolf
  rom: 
  room: ROOM002
  position: 1
- cabinetDBName: jumpbug
  rom: 
  room: ROOM002
  position: 2
- cabinetDBName: btoads
  rom: 
  room: ROOM003
  position: 0
- cabinetDBName: pow
  rom: 
  room: ROOM003
  position: 1
- cabinetDBName: gaplus
  rom: 
  room: ROOM003
  position: 2
- cabinetDBName: crsword
  rom: 
  room: ROOM003
  position: 3
- cabinetDBName: slyspy
  rom: 
  room: ROOM003
  position: 4
- cabinetDBName: timesold
  rom: 
  room: ROOM003
  position: 5
- cabinetDBName: gunforce
  rom: 
  room: ROOM003
  position: 6
- cabinetDBName: twincobr
  rom: 
  room: ROOM003
  position: 7
- cabinetDBName: ffight
  rom: 
  room: ROOM003
  position: 8
- cabinetDBName: ddragon
  rom: 
  room: ROOM003
  position: 9
- cabinetDBName: forgottn
  rom: 
  room: ROOM018
  position: 0
- cabinetDBName: mslug2
  rom: 
  room: ROOM018
  position: 1
- cabinetDBName: galaga88
  rom: 
  room: ROOM018
  position: 2
- cabinetDBName: alien3 FXD
  rom: 
  room: ROOM018
  position: 3
- cabinetDBName: altbeast_v2
  rom: 
  room: ROOM018
  position: 4
- cabinetDBName: spacegun
  rom: 
  room: ROOM018
  position: 5
- cabinetDBName: bouldash
  rom: 
  room: ROOM018
  position: 6
- cabinetDBName: tailg
  rom: 
  room: ROOM018
  position: 7
- cabinetDBName: mslug
  rom: 
  room: ROOM018
  position: 8
- cabinetDBName: simpsn2p
  rom: 
  room: ROOM018
  position: 9
- cabinetDBName: fastfred
  rom: 
  room: ROOM018
  position: 10
- cabinetDBName: a3stooges
  rom: 
  room: ROOM018
  position: 11
- cabinetDBName: smashtv
  rom: 
  room: ROOM018
  position: 12
- cabinetDBName: hogalley
  rom: 
  room: ROOM018
  position: 13
- cabinetDBName: hangon
  rom: 
  room: ROOM018
  position: 14
- cabinetDBName: radm
  rom: 
  room: ROOM018
  position: 15
- cabinetDBName: dinou
  rom: 
  room: ROOM018
  position: 16
- cabinetDBName: gunforce
  rom: 
  room: ROOM018
  position: 17
- cabinetDBName: hbarrel
  rom: 
  room: ROOM018
  position: 18
- cabinetDBName: spacegun
  rom: 
  room: ROOM018
  position: 19
- cabinetDBName: sdungeon
  rom: 
  room: ROOM018
  position: 20
- cabinetDBName: revx
  rom: 
  room: ROOM018
  position: 21
- cabinetDBName: gunforce
  rom: 
  room: ROOM018
  position: 22
- cabinetDBName: blktiger
  rom: 
  room: ROOM018
  position: 23
- cabinetDBName: kinst
  rom: 
  room: ROOM018
  position: 24
- cabinetDBName: toutrun
  rom: 
  room: ROOM018
  position: 25
- cabinetDBName: robocop
  rom: 
  room: ROOM018
  position: 26
- cabinetDBName: sidearms
  rom: 
  room: ROOM018
  position: 27
- cabinetDBName: sharriersitdown
  rom: 
  room: ROOM018
  position: 28
- cabinetDBName: mslug2
  rom: 
  room: ROOM018
  position: 29
- cabinetDBName: revx
  rom: 
  room: ROOM018
  position: 30
- cabinetDBName: lwings
  rom: 
  room: ROOM018
  position: 31
- cabinetDBName: punchout
  rom: 
  room: ROOM018
  position: 32
- cabinetDBName: cstlevna
  rom: 
  room: ROOM018
  position: 33
- cabinetDBName: sharriersitdown
  rom: 
  room: ROOM018
  position: 34
- cabinetDBName: harddriv
  rom: 
  room: ROOM018
  position: 35
- cabinetDBName: mslug4
  rom: 
  room: ROOM018
  position: 36
- cabinetDBName: bubbles
  rom: 
  room: ROOM018
  position: 37
- cabinetDBName: airwolf
  rom: 
  room: ROOM018
  position: 38
- cabinetDBName: a3countb
  rom: 
  room: ROOM018
  position: 39
- cabinetDBName: term2 moviegun
  rom: 
  room: ROOM018
  position: 40
- cabinetDBName: rambo3
  rom: 
  room: ROOM018
  position: 41
- cabinetDBName: aburner
  rom: 
  room: ROOM018
  position: 42
- cabinetDBName: contra
  rom: 
  room: ROOM018
  position: 43
- cabinetDBName: armorcar
  rom: 
  room: ROOM018
  position: 44
- cabinetDBName: polepos2
  rom: 
  room: ROOM018
  position: 45
- cabinetDBName: mp_gaxe2
  rom: 
  room: ROOM018
  position: 46
- cabinetDBName: lethalen
  rom: 
  room: ROOM018
  position: 47
- cabinetDBName: baddudes
  rom: 
  room: ROOM018
  position: 48
- cabinetDBName: clshroad
  rom: 
  room: ROOM018
  position: 49
- cabinetDBName: ddragon
  rom: 
  room: ROOM018
  position: 50
- cabinetDBName: jackal
  rom: 
  room: ROOM018
  position: 51
- cabinetDBName: lethalen
  rom: 
  room: ROOM004
  position: 0
- cabinetDBName: pow
  rom: 
  room: ROOM004
  position: 1
- cabinetDBName: aliensyn
  rom: 
  room: ROOM004
  position: 2
- cabinetDBName: btoads
  rom: 
  room: ROOM004
  position: 3
- cabinetDBName: totcarn
  rom: 
  room: ROOM004
  position: 4
- cabinetDBName: superman
  rom: 
  room: ROOM004
  position: 5
- cabinetDBName: altbeast_v2
  rom: 
  room: ROOM004
  position: 6
- cabinetDBName: samsho5
  rom: 
  room: ROOM004
  position: 7
- cabinetDBName: ikari
  rom: 
  room: ROOM004
  position: 8
- cabinetDBName: cracksht
  rom: 
  room: ROOM004
  position: 9
- cabinetDBName: amidar
  rom: 
  room: ROOM004
  position: 10
- cabinetDBName: subroc3d
  rom: 
  room: ROOM004
  position: 11
- cabinetDBName: mooncrst
  rom: 
  room: ROOM004
  position: 12
- cabinetDBName: dspirit
  rom: 
  room: ROOM004
  position: 13
- cabinetDBName: zaxxon
  rom: 
  room: ROOM006
  position: 0
- cabinetDBName: punchout
  rom: 
  room: ROOM006
  position: 1
- cabinetDBName: luckywld
  rom: 
  room: ROOM006
  position: 2
- cabinetDBName: cheyenne
  rom: 
  room: ROOM005
  position: 0
- cabinetDBName: toutrun
  rom: 
  room: ROOM005
  position: 1
- cabinetDBName: dragoonj
  rom: 
  room: ROOM005
  position: 2
- cabinetDBName: slyspy
  rom: 
  room: ROOM005
  position: 3
- cabinetDBName: searchar
  rom: 
  room: ROOM005
  position: 4
- cabinetDBName: krull
  rom: 
  room: ROOM005
  position: 5
- cabinetDBName: radm
  rom: 
  room: ROOM005
  position: 6
- cabinetDBName: narc
  rom: 
  room: ROOM005
  position: 7
- cabinetDBName: xybots
  rom: 
  room: ROOM005
  position: 9
- cabinetDBName: othunder
  rom: 
  room: ROOM005
  position: 10
- cabinetDBName: digdug
  rom: 
  room: ROOM005
  position: 11
- cabinetDBName: pitfall2
  rom: 
  room: room001
  position: 7
- cabinetDBName: armorcar
  rom: 
  room: ROOM005
  position: 8
- cabinetDBName: mslug4
  rom: 
  room: ROOM008
  position: 0
- cabinetDBName: msword
  rom: 
  room: ROOM008
  position: 1
- cabinetDBName: phoenix
  rom: 
  room: ROOM008
  position: 2
- cabinetDBName: cracksht
  rom: 
  room: ROOM008
  position: 3
- cabinetDBName: docvadergyruss
  rom: 
  room: ROOM008
  position: 4
- cabinetDBName: dbz
  rom: 
  room: ROOM008
  position: 5
- cabinetDBName: vsskykid
  rom: 
  room: ROOM008
  position: 6
- cabinetDBName: rocnrope
  rom: 
  room: ROOM008
  position: 7
- cabinetDBName: inthunt
  rom: 
  room: ROOM008
  position: 8
- cabinetDBName: starwars
  rom: 
  room: ROOM008
  position: 9
- cabinetDBName: umk3
  rom: 
  room: ROOM009
  position: 0
- cabinetDBName: bbmanw
  rom: 
  room: ROOM009
  position: 1
- cabinetDBName: mazinger
  rom: 
  room: ROOM009
  position: 2
- cabinetDBName: smashtv
  rom: 
  room: ROOM009
  position: 3
- cabinetDBName: gigawing
  rom: 
  room: ROOM009
  position: 4
- cabinetDBName: dotron
  rom: 
  room: ROOM009
  position: 5
- cabinetDBName: carnival
  rom: 
  room: ROOM009
  position: 6
- cabinetDBName: batman
  rom: 
  room: ROOM009
  position: 7
- cabinetDBName: cstlevna
  rom: 
  room: ROOM016
  position: 0
- cabinetDBName: polepos2
  rom: 
  room: ROOM016
  position: 1
- cabinetDBName: bionicc
  rom: 
  room: ROOM016
  position: 2
- cabinetDBName: amidar
  rom: 
  room: ROOM016
  position: 3
- cabinetDBName: chasehq
  rom: 
  room: ROOM016
  position: 4
- cabinetDBName: pitfight
  rom: 
  room: ROOM016
  position: 5
- cabinetDBName: altbeast_v2
  rom: 
  room: ROOM016
  position: 6
- cabinetDBName: kinst
  rom: 
  room: ROOM016
  position: 7
- cabinetDBName: stratvox
  rom: 
  room: ROOM016
  position: 8
- cabinetDBName: dkong3
  rom: 
  room: ROOM016
  position: 9
- cabinetDBName: esb
  rom: 
  room: ROOM016
  position: 10
- cabinetDBName: claypign
  rom: 
  room: ROOM016
  position: 11
- cabinetDBName: Revx_gunsaway
  rom: 
  room: ROOM001
  position: 4
- cabinetDBName: a1942
  rom: 
  room: ROOM007
  position: 0
- cabinetDBName: a1943
  rom: 
  room: ROOM007
  position: 1
- cabinetDBName: a3Wonders
  rom: 
  room: ROOM007
  position: 2
- cabinetDBName: aburnerDX
  rom: 
  room: ROOM007
  position: 3
- cabinetDBName: aliens
  rom: 
  room: ROOM007
  position: 4
- cabinetDBName: apb
  rom: 
  room: ROOM007
  position: 5
- cabinetDBName: area51
  rom: 
  room: ROOM007
  position: 6
- cabinetDBName: arkanoid
  rom: 
  room: ROOM007
  position: 7
- cabinetDBName: assault
  rom: 
  room: ROOM007
  position: 8
- cabinetDBName: astdelux
  rom: 
  room: ROOM007
  position: 9
- cabinetDBName: asteroid
  rom: 
  room: ROOM007
  position: 10
- cabinetDBName: astrob
  rom: 
  room: ROOM010
  position: 0
- cabinetDBName: bbusters
  rom: 
  room: ROOM010
  position: 1
- cabinetDBName: berzerk
  rom: 
  room: ROOM010
  position: 2
- cabinetDBName: bloodbro
  rom: 
  room: ROOM010
  position: 3
- cabinetDBName: blstroid
  rom: 
  room: ROOM010
  position: 4
- cabinetDBName: bombjack
  rom: 
  room: ROOM010
  position: 5
- cabinetDBName: brkthru
  rom: 
  room: ROOM010
  position: 6
- cabinetDBName: broke kong
  rom: 
  room: ROOM010
  position: 7
- cabinetDBName: btime
  rom: 
  room: ROOM010
  position: 8
- cabinetDBName: bucky
  rom: 
  room: ROOM010
  position: 9
- cabinetDBName: bwidow
  rom: 
  room: ROOM010
  position: 10
- cabinetDBName: bzone
  rom: 
  room: ROOM010
  position: 11
- cabinetDBName: cabal
  rom: 
  room: ROOM014
  position: 0
- cabinetDBName: cadash
  rom: 
  room: ROOM014
  position: 1
- cabinetDBName: calibr50
  rom: 
  room: ROOM014
  position: 2
- cabinetDBName: captaven
  rom: 
  room: ROOM014
  position: 3
- cabinetDBName: carnevil
  rom: 
  room: ROOM014
  position: 4
- cabinetDBName: ccastles
  rom: 
  room: ROOM014
  position: 5
- cabinetDBName: cclimber
  rom: 
  room: ROOM014
  position: 6
- cabinetDBName: centiped_alt
  rom: 
  room: ROOM014
  position: 7
- cabinetDBName: chiller
  rom: 
  room: ROOM014
  position: 8
- cabinetDBName: chplftbl
  rom: 
  room: ROOM014
  position: 9
- cabinetDBName: cninja
  rom: 
  room: ROOM014
  position: 10
- cabinetDBName: cobracom
  rom: 
  room: ROOM014
  position: 11
- cabinetDBName: combat
  rom: 
  room: ROOM014
  position: 12
- cabinetDBName: commando
  rom: 
  room: ROOM014
  position: 13
- cabinetDBName: crimec
  rom: 
  room: ROOM011
  position: 0
- cabinetDBName: crossbow
  rom: 
  room: ROOM011
  position: 1
- cabinetDBName: ctribe
  rom: 
  room: ROOM011
  position: 2
- cabinetDBName: dassault
  rom: 
  room: ROOM011
  position: 3
- cabinetDBName: dbreed
  rom: 
  room: ROOM011
  position: 4
- cabinetDBName: ddragon2
  rom: 
  room: ROOM011
  position: 5
- cabinetDBName: defender
  rom: 
  room: ROOM011
  position: 6
- cabinetDBName: devstors
  rom: 
  room: ROOM011
  position: 7
- cabinetDBName: dkong
  rom: 
  room: ROOM011
  position: 8
- cabinetDBName: dondoko
  rom: 
  room: ROOM011
  position: 9
- cabinetDBName: dotron sit
  rom: 
  room: ROOM011
  position: 10
- cabinetDBName: dragnblz
  rom: 
  room: ROOM011
  position: 11
```
