### ISSUE TITLE
Variable injection on cabinet's AGEBasic

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#298]
Using CDL, inject variables to the cabinet AGEBasic execution:

```yaml
agebasic:
  active: true
  debug: true
  after-insert-coin: main.bas
  variables:
    - name: amplitude
      type: number
      value: 0.1
    - name: duration
      type: number
      value: 0.05
      
```
