### ISSUE TITLE
Console configuration crash in some installations

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#475]
https://discord.com/channels/1066438667989696645/1070495784816083014/1238983604252708925

crusher124 — Yesterday at 7:12 PM
AOJ v0.5.5 When trying to set global configurations at the control console, AOJ will freeze.
configuration.yaml:

```yaml
npc:
  status: enabled
audio:
  background:
    volume-percent: 50
    muted: false
  in-game-background:
    volume-percent: 20
    muted: false
locomotion:
  teleport-enabled: true
  speed: 2
  turn-speed: 80
  snap-turn-amout: 30
  snap-turn-active: false
player:
  height: 1.0
  scale: 0.9
agebasic:
  after-load: Random Posters White Light.bas
  active: false
  debug: true
```
