### ISSUE TITLE
AGEBasic events

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#573]
Create a trigger system using Unity's event internal system to execute AGEBasic programs when an event is raised.

AGEBasic cabinets events #453
AGEBasic function to know the rom name #572

```yaml
agebasic:
  on-event:
    - INSERT-COIN: insert-coin.bas
    - GAME-CHANGE: game-change.bas
    - ...
```
