### ISSUE TITLE
Any cabinet part could have an audio speaker

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#603]
... to play mp3, ogg or wav files.

Add the next AGEBasic functions:

```
CabPartAudioVolume
CabPartAudioDistance
CabPartAudioFile
CabPartAudioLoop
CabPartAudioPlay
CabPartAudioStop
CabPartAudioPause
```
YAML specification to add to a `part`:
```yaml
audio:
  file: "gong.mp3"
  volume: 0.5
  loop: false
  distance:
    min: 1
    max: 5
```
