### ISSUE TITLE
Cabinet rotation

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#611]
needed for warehouse and bing cabinets, to face to the position the user wants
Registry:
```yaml
SLOT         :   0-cabsomething
GAME         :   street fighter II
ORIENTATION  :   0°
```

![image](https://github.com/user-attachments/assets/dc524cd4-332c-4f25-8587-5e597324285f)
