### ISSUE TITLE
Change the screen name

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#621]
The screen gameobject name is assigned by default and the cabinet artist can access the part to rotate or translate it for example.

 Add a new property `name` to the crt subdocument:

```yaml
crt:
  type: 19i
  orientation: horizontal
  name: screen
  screen:
    shader: clean
    damage: high
    inverty: false
    invertx: true
```
