### ISSUE TITLE
The parts do not show textures

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#653]
this combination doesn't show the texture:
```yaml
  - name: xxx
    art:
      file: xxx.jpg
    color:
      r: 238
      g: 232
      b: 176
```
