### ISSUE TITLE
conditional cabinet events in AGEBasic 

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#703]
Conditional execution of events: execute it if a variable has a value:
 
```yaml
    - event: on-control-active-press
      libretro-id: JOYPAD_B
      condition:
          variable: myvariable
          value: 30
      program: myprogram.bas
```
The `myvariable` variable should exists and have the value `30` to execute `myprogram.bas`

**Comment by curif** [comment]
```yaml
- event: on-control-active-press
  libretro-id: JOYPAD_B
  condition:
    and:
      - variable: myvariable1
        operator: ">"
        value: 30
      - or:
          - variable: myvariable2
            operator: "="
            value: 10
          - variable: myvariable3
            operator: "<"
            compare-to: myvariable4
  program: myprogram.bas
```
